/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAuth_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   auth/v1
// Description:
//   Logs users in and out, and retrieves a user's details.

#import "GTLAuthConstants.m"

#import "GTLAuthConnectasticAuthReq.m"
#import "GTLAuthConnectasticAuthRsp.m"
#import "GTLAuthConnectasticRecordInvitationsReq.m"
#import "GTLAuthConnectasticRegisterReq.m"
#import "GTLAuthConnectasticWaitlistReq.m"

#import "GTLQueryAuth.m"
#import "GTLServiceAuth.m"
