/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAuthConnectasticRecordInvitationsReq.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   auth/v1
// Description:
//   Logs users in and out, and retrieves a user's details.
// Classes:
//   GTLAuthConnectasticRecordInvitationsReq (0 custom class methods, 2 custom properties)

#import "GTLAuthConnectasticRecordInvitationsReq.h"

// ----------------------------------------------------------------------------
//
//   GTLAuthConnectasticRecordInvitationsReq
//

@implementation GTLAuthConnectasticRecordInvitationsReq
@dynamic inviteeFbIds, inviterFbId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"invitee_fb_ids", @"inviteeFbIds",
      @"inviter_fb_id", @"inviterFbId",
      nil];
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[NSNumber class]
                                forKey:@"invitee_fb_ids"];
  return map;
}

@end
