/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAuthConnectasticRegisterReq.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   auth/v1
// Description:
//   Logs users in and out, and retrieves a user's details.
// Classes:
//   GTLAuthConnectasticRegisterReq (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLAuthConnectasticRegisterReq
//

@interface GTLAuthConnectasticRegisterReq : GTLObject
@property (nonatomic, retain) NSNumber *fbId;  // longLongValue
@property (nonatomic, copy) NSString *invitationKey;
@property (nonatomic, copy) NSString *token;
@end
