/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAuthConnectasticAuthRsp.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   auth/v1
// Description:
//   Logs users in and out, and retrieves a user's details.
// Classes:
//   GTLAuthConnectasticAuthRsp (0 custom class methods, 6 custom properties)

#import "GTLAuthConnectasticAuthRsp.h"

// ----------------------------------------------------------------------------
//
//   GTLAuthConnectasticAuthRsp
//

@implementation GTLAuthConnectasticAuthRsp
@dynamic email, error, hasInvites, invites, loggedIn, name;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"has_invites", @"hasInvites",
      @"logged_in", @"loggedIn",
      nil];
  return map;
}

@end
