/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAuthConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   auth/v1
// Description:
//   Logs users in and out, and retrieves a user's details.

#import "GTLAuthConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeAuthUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
