/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAuthConnectasticWaitlistReq.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   auth/v1
// Description:
//   Logs users in and out, and retrieves a user's details.
// Classes:
//   GTLAuthConnectasticWaitlistReq (0 custom class methods, 2 custom properties)

#import "GTLAuthConnectasticWaitlistReq.h"

// ----------------------------------------------------------------------------
//
//   GTLAuthConnectasticWaitlistReq
//

@implementation GTLAuthConnectasticWaitlistReq
@dynamic email, name;
@end
