/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAuth.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   auth/v1
// Description:
//   Logs users in and out, and retrieves a user's details.

#import "GTLAuthConstants.h"

#import "GTLAuthConnectasticAuthReq.h"
#import "GTLAuthConnectasticAuthRsp.h"
#import "GTLAuthConnectasticRecordInvitationsReq.h"
#import "GTLAuthConnectasticRegisterReq.h"

#import "GTLQueryAuth.h"
#import "GTLServiceAuth.h"
