/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAuthConnectasticAuthRsp.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   auth/v1
// Description:
//   Logs users in and out, and retrieves a user's details.
// Classes:
//   GTLAuthConnectasticAuthRsp (0 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLAuthConnectasticAuthRsp
//

@interface GTLAuthConnectasticAuthRsp : GTLObject
@property (nonatomic, copy) NSString *email;
@property (nonatomic, retain) NSNumber *error;  // longLongValue
@property (nonatomic, retain) NSNumber *hasInvites;  // boolValue
@property (nonatomic, retain) NSNumber *invites;  // longLongValue
@property (nonatomic, retain) NSNumber *loggedIn;  // boolValue
@property (nonatomic, copy) NSString *name;
@property (nonatomic, copy) NSString *token;
@end
