/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAuthConnectasticRegisterReq.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   auth/v1
// Description:
//   Logs users in and out, and retrieves a user's details.
// Classes:
//   GTLAuthConnectasticRegisterReq (0 custom class methods, 3 custom properties)

#import "GTLAuthConnectasticRegisterReq.h"

// ----------------------------------------------------------------------------
//
//   GTLAuthConnectasticRegisterReq
//

@implementation GTLAuthConnectasticRegisterReq
@dynamic fbId, invitationKey, token;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"fbId" : @"fb_id",
    @"invitationKey" : @"invitation_key"
  };
  return map;
}

@end
