/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAuthConnectasticRecordInvitationsReq.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   auth/v1
// Description:
//   Logs users in and out, and retrieves a user's details.
// Classes:
//   GTLAuthConnectasticRecordInvitationsReq (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLAuthConnectasticRecordInvitationsReq
//

@interface GTLAuthConnectasticRecordInvitationsReq : GTLObject
@property (nonatomic, retain) NSArray *inviteeFbIds;  // of NSNumber (longLongValue)
@property (nonatomic, retain) NSNumber *inviterFbId;  // longLongValue
@end
