/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLAuthConnectasticRecordInvitationsReq.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   auth/v1
// Description:
//   Logs users in and out, and retrieves a user's details.
// Classes:
//   GTLAuthConnectasticRecordInvitationsReq (0 custom class methods, 2 custom properties)

#import "GTLAuthConnectasticRecordInvitationsReq.h"

// ----------------------------------------------------------------------------
//
//   GTLAuthConnectasticRecordInvitationsReq
//

@implementation GTLAuthConnectasticRecordInvitationsReq
@dynamic inviteeFbIds, inviterFbId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"inviteeFbIds" : @"invitee_fb_ids",
    @"inviterFbId" : @"inviter_fb_id"
  };
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"invitee_fb_ids" : [NSNumber class]
  };
  return map;
}

@end
