/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLDeviceregistrationConnectasticDeviceExistsRsp.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   deviceregistration/v1
// Description:
//   Registers and un-registers devices
// Classes:
//   GTLDeviceregistrationConnectasticDeviceExistsRsp (0 custom class methods, 1 custom properties)

#import "GTLDeviceregistrationConnectasticDeviceExistsRsp.h"

// ----------------------------------------------------------------------------
//
//   GTLDeviceregistrationConnectasticDeviceExistsRsp
//

@implementation GTLDeviceregistrationConnectasticDeviceExistsRsp
@dynamic exists;
@end
