/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLDeviceregistrationConnectasticDeviceExistsRsp.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   deviceregistration/v1
// Description:
//   Registers and un-registers devices
// Classes:
//   GTLDeviceregistrationConnectasticDeviceExistsRsp (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLDeviceregistrationConnectasticDeviceExistsRsp
//

@interface GTLDeviceregistrationConnectasticDeviceExistsRsp : GTLObject
@property (nonatomic, retain) NSNumber *exists;  // boolValue
@end
