/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLDeviceregistration_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   deviceregistration/v1
// Description:
//   Registers and un-registers devices

#import "GTLDeviceregistrationConstants.m"

#import "GTLDeviceregistrationConnectasticDeviceExistsRsp.m"
#import "GTLDeviceregistrationConnectasticDeviceReq.m"

#import "GTLQueryDeviceregistration.m"
#import "GTLServiceDeviceregistration.m"
