/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLDeviceregistration.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   deviceregistration/v1
// Description:
//   Registers and un-registers devices

#import "GTLDeviceregistrationConstants.h"

#import "GTLDeviceregistrationConnectasticDeviceExistsRsp.h"
#import "GTLDeviceregistrationConnectasticDeviceReq.h"

#import "GTLQueryDeviceregistration.h"
#import "GTLServiceDeviceregistration.h"
