/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLDeviceregistrationConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   deviceregistration/v1
// Description:
//   Registers and un-registers devices

#import "GTLDeviceregistrationConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeDeviceregistrationUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
