/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventsConnectasticRecommendationRsp.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events
// Classes:
//   GTLEventsConnectasticRecommendationRsp (0 custom class methods, 9 custom properties)

#import "GTLEventsConnectasticRecommendationRsp.h"

#import "GTLEventsConnectasticVenueRsp.h"

// ----------------------------------------------------------------------------
//
//   GTLEventsConnectasticRecommendationRsp
//

@implementation GTLEventsConnectasticRecommendationRsp
@dynamic areaId, avgDuration, avgHumanReadableDuration, durations,
         humanReadableDurations, latitude, longitude, name, venues;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"areaId" : @"area_id",
    @"avgDuration" : @"avg_duration",
    @"avgHumanReadableDuration" : @"avg_human_readable_duration",
    @"humanReadableDurations" : @"human_readable_durations"
  };
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"durations" : [NSNumber class],
    @"human_readable_durations" : [NSString class],
    @"venues" : [GTLEventsConnectasticVenueRsp class]
  };
  return map;
}

@end
