/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLEventsConnectasticEventsRsp.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events
// Classes:
//   GTLEventsConnectasticEventsRsp (0 custom class methods, 2 custom properties)

#import "GTLEventsConnectasticEventsRsp.h"

#import "GTLEventsConnectasticEventRsp.h"

// ----------------------------------------------------------------------------
//
//   GTLEventsConnectasticEventsRsp
//

@implementation GTLEventsConnectasticEventsRsp
@dynamic ownedEvents, participatingEvents;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"owned_events", @"ownedEvents",
      @"participating_events", @"participatingEvents",
      nil];
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      [GTLEventsConnectasticEventRsp class], @"owned_events",
      [GTLEventsConnectasticEventRsp class], @"participating_events",
      nil];
  return map;
}

@end
