/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLEventsConnectasticVenueRsp.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events
// Classes:
//   GTLEventsConnectasticVenueRsp (0 custom class methods, 14 custom properties)

#import "GTLEventsConnectasticVenueRsp.h"

// ----------------------------------------------------------------------------
//
//   GTLEventsConnectasticVenueRsp
//

@implementation GTLEventsConnectasticVenueRsp
@dynamic address, facebookPage, latitude, longitude, name, photos, postcode,
         price, rating, reservationUrl, reservationsAvailable, source, type,
         venueId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"facebook_page", @"facebookPage",
      @"reservations_available", @"reservationsAvailable",
      @"reservation_url", @"reservationUrl",
      @"venue_id", @"venueId",
      nil];
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[NSString class]
                                forKey:@"photos"];
  return map;
}

@end
