/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventsConnectasticEventRsp.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events
// Classes:
//   GTLEventsConnectasticEventRsp (0 custom class methods, 11 custom properties)

#import "GTLEventsConnectasticEventRsp.h"

#import "GTLEventsConnectasticPersonRsp.h"
#import "GTLEventsConnectasticRecommendationRsp.h"
#import "GTLEventsConnectasticVenueRsp.h"

// ----------------------------------------------------------------------------
//
//   GTLEventsConnectasticEventRsp
//

@implementation GTLEventsConnectasticEventRsp
@dynamic createdAt, date, eventId, isOwner, name, owner, participantFbIds,
         participants, recommendations, selectedVenue, type;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"createdAt" : @"created_at",
    @"eventId" : @"event_id",
    @"isOwner" : @"is_owner",
    @"participantFbIds" : @"participant_fb_ids",
    @"selectedVenue" : @"selected_venue"
  };
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"participant_fb_ids" : [NSNumber class],
    @"participants" : [GTLEventsConnectasticPersonRsp class],
    @"recommendations" : [GTLEventsConnectasticRecommendationRsp class]
  };
  return map;
}

@end
