/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventsConnectasticParticipantReq.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events
// Classes:
//   GTLEventsConnectasticParticipantReq (0 custom class methods, 3 custom properties)

#import "GTLEventsConnectasticParticipantReq.h"

// ----------------------------------------------------------------------------
//
//   GTLEventsConnectasticParticipantReq
//

@implementation GTLEventsConnectasticParticipantReq
@dynamic address, fbId, transport;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"fbId" : @"fb_id"
  };
  return map;
}

@end
