/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLEventsConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events

#import "GTLEventsConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeEventsUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
