/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLEventsConnectasticPersonRsp.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events
// Classes:
//   GTLEventsConnectasticPersonRsp (0 custom class methods, 6 custom properties)

#import "GTLEventsConnectasticPersonRsp.h"

// ----------------------------------------------------------------------------
//
//   GTLEventsConnectasticPersonRsp
//

@implementation GTLEventsConnectasticPersonRsp
@dynamic address, fbId, latitude, longitude, name, transport;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"fb_id"
                                forKey:@"fbId"];
  return map;
}

@end
