/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventsConnectasticVenueRsp.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events
// Classes:
//   GTLEventsConnectasticVenueRsp (0 custom class methods, 8 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLEventsConnectasticVenueRsp
//

@interface GTLEventsConnectasticVenueRsp : GTLObject
@property (nonatomic, copy) NSString *fbId;
@property (nonatomic, retain) NSNumber *latitude;  // doubleValue
@property (nonatomic, retain) NSNumber *longitude;  // doubleValue
@property (nonatomic, copy) NSString *name;
@property (nonatomic, copy) NSString *reservationUrl;
@property (nonatomic, retain) NSNumber *reservationsAvailable;  // boolValue
@property (nonatomic, copy) NSString *type;
@property (nonatomic, copy) NSString *venueId;
@end
