/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLEvents.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events

#import "GTLEventsConstants.h"

#import "GTLEventsConnectasticCreateEventRsp.h"
#import "GTLEventsConnectasticEventRsp.h"
#import "GTLEventsConnectasticEventsRsp.h"
#import "GTLEventsConnectasticModifyEventReq.h"
#import "GTLEventsConnectasticNewEventReq.h"
#import "GTLEventsConnectasticParticipantReq.h"
#import "GTLEventsConnectasticPersonRsp.h"
#import "GTLEventsConnectasticRecommendationRsp.h"
#import "GTLEventsConnectasticUpdateParticipantsReq.h"
#import "GTLEventsConnectasticVenueRsp.h"

#import "GTLQueryEvents.h"
#import "GTLServiceEvents.h"
