/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventsConnectasticEventsRsp.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events
// Classes:
//   GTLEventsConnectasticEventsRsp (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLEventsConnectasticEventRsp;

// ----------------------------------------------------------------------------
//
//   GTLEventsConnectasticEventsRsp
//

@interface GTLEventsConnectasticEventsRsp : GTLObject
@property (nonatomic, retain) NSArray *ownedEvents;  // of GTLEventsConnectasticEventRsp
@property (nonatomic, retain) NSArray *participatingEvents;  // of GTLEventsConnectasticEventRsp
@end
