/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLEventsConnectasticEventRsp.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events
// Classes:
//   GTLEventsConnectasticEventRsp (0 custom class methods, 11 custom properties)

#import "GTLEventsConnectasticEventRsp.h"

#import "GTLEventsConnectasticPersonRsp.h"
#import "GTLEventsConnectasticRecommendationRsp.h"
#import "GTLEventsConnectasticVenueRsp.h"

// ----------------------------------------------------------------------------
//
//   GTLEventsConnectasticEventRsp
//

@implementation GTLEventsConnectasticEventRsp
@dynamic createdAt, date, eventId, isOwner, name, owner, participantFbIds,
         participants, recommendations, selectedVenue, type;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"created_at", @"createdAt",
      @"event_id", @"eventId",
      @"is_owner", @"isOwner",
      @"participant_fb_ids", @"participantFbIds",
      @"selected_venue", @"selectedVenue",
      nil];
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      [NSNumber class], @"participant_fb_ids",
      [GTLEventsConnectasticPersonRsp class], @"participants",
      [GTLEventsConnectasticRecommendationRsp class], @"recommendations",
      nil];
  return map;
}

@end
