/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventsConnectasticUpdateParticipantsReq.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events
// Classes:
//   GTLEventsConnectasticUpdateParticipantsReq (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLEventsConnectasticParticipantReq;

// ----------------------------------------------------------------------------
//
//   GTLEventsConnectasticUpdateParticipantsReq
//

@interface GTLEventsConnectasticUpdateParticipantsReq : GTLObject
@property (nonatomic, copy) NSString *eventId;
@property (nonatomic, retain) NSArray *participants;  // of GTLEventsConnectasticParticipantReq
@property (nonatomic, copy) NSString *token;
@end
