/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLEventsConnectasticPersonRsp.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events
// Classes:
//   GTLEventsConnectasticPersonRsp (0 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLEventsConnectasticPersonRsp
//

@interface GTLEventsConnectasticPersonRsp : GTLObject
@property (copy) NSString *address;
@property (retain) NSNumber *fbId;  // longLongValue
@property (copy) NSString *latitude;
@property (copy) NSString *longitude;
@property (copy) NSString *name;
@property (copy) NSString *transport;
@end
