/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLEventsConnectasticNewEventReq.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events
// Classes:
//   GTLEventsConnectasticNewEventReq (0 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLEventsConnectasticParticipantReq;

// ----------------------------------------------------------------------------
//
//   GTLEventsConnectasticNewEventReq
//

@interface GTLEventsConnectasticNewEventReq : GTLObject
@property (retain) NSNumber *date;  // longLongValue
@property (copy) NSString *name;
@property (retain) GTLEventsConnectasticParticipantReq *owner;
@property (retain) NSArray *participants;  // of GTLEventsConnectasticParticipantReq
@property (copy) NSString *token;
@property (copy) NSString *type;
@end
