/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLEventsConnectasticRecommendationRsp.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events
// Classes:
//   GTLEventsConnectasticRecommendationRsp (0 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLEventsConnectasticVenueRsp;

// ----------------------------------------------------------------------------
//
//   GTLEventsConnectasticRecommendationRsp
//

@interface GTLEventsConnectasticRecommendationRsp : GTLObject
@property (copy) NSString *areaId;
@property (retain) NSArray *durations;  // of NSNumber (doubleValue)
@property (retain) NSArray *humanReadableDurations;  // of NSString
@property (retain) NSNumber *latitude;  // doubleValue
@property (retain) NSNumber *longitude;  // doubleValue
@property (copy) NSString *name;
@property (retain) NSArray *venues;  // of GTLEventsConnectasticVenueRsp
@end
