/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLEventsConnectasticRecommendationRsp.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events
// Classes:
//   GTLEventsConnectasticRecommendationRsp (0 custom class methods, 7 custom properties)

#import "GTLEventsConnectasticRecommendationRsp.h"

#import "GTLEventsConnectasticVenueRsp.h"

// ----------------------------------------------------------------------------
//
//   GTLEventsConnectasticRecommendationRsp
//

@implementation GTLEventsConnectasticRecommendationRsp
@dynamic areaId, durations, humanReadableDurations, latitude, longitude, name,
         venues;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"area_id", @"areaId",
      @"human_readable_durations", @"humanReadableDurations",
      nil];
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      [NSNumber class], @"durations",
      [NSString class], @"human_readable_durations",
      [GTLEventsConnectasticVenueRsp class], @"venues",
      nil];
  return map;
}

@end
