/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLEventsConnectasticUpdateParticipantsReq.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events
// Classes:
//   GTLEventsConnectasticUpdateParticipantsReq (0 custom class methods, 3 custom properties)

#import "GTLEventsConnectasticUpdateParticipantsReq.h"

#import "GTLEventsConnectasticParticipantReq.h"

// ----------------------------------------------------------------------------
//
//   GTLEventsConnectasticUpdateParticipantsReq
//

@implementation GTLEventsConnectasticUpdateParticipantsReq
@dynamic eventId, participants, token;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"event_id"
                                forKey:@"eventId"];
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLEventsConnectasticParticipantReq class]
                                forKey:@"participants"];
  return map;
}

@end
