/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLEventsConnectasticVenueRsp.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events
// Classes:
//   GTLEventsConnectasticVenueRsp (0 custom class methods, 14 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLEventsConnectasticVenueRsp
//

@interface GTLEventsConnectasticVenueRsp : GTLObject
@property (copy) NSString *address;
@property (copy) NSString *facebookPage;
@property (retain) NSNumber *latitude;  // doubleValue
@property (retain) NSNumber *longitude;  // doubleValue
@property (copy) NSString *name;
@property (retain) NSArray *photos;  // of NSString
@property (copy) NSString *postcode;
@property (retain) NSNumber *price;  // longLongValue
@property (retain) NSNumber *rating;  // doubleValue
@property (copy) NSString *reservationUrl;
@property (retain) NSNumber *reservationsAvailable;  // boolValue
@property (copy) NSString *source;
@property (copy) NSString *type;
@property (copy) NSString *venueId;
@end
