/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEventsConnectasticEventsRsp.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events
// Classes:
//   GTLEventsConnectasticEventsRsp (0 custom class methods, 2 custom properties)

#import "GTLEventsConnectasticEventsRsp.h"

#import "GTLEventsConnectasticEventRsp.h"

// ----------------------------------------------------------------------------
//
//   GTLEventsConnectasticEventsRsp
//

@implementation GTLEventsConnectasticEventsRsp
@dynamic ownedEvents, participatingEvents;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"ownedEvents" : @"owned_events",
    @"participatingEvents" : @"participating_events"
  };
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"owned_events" : [GTLEventsConnectasticEventRsp class],
    @"participating_events" : [GTLEventsConnectasticEventRsp class]
  };
  return map;
}

@end
