/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLEventsConnectasticCreateEventRsp.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events
// Classes:
//   GTLEventsConnectasticCreateEventRsp (0 custom class methods, 1 custom properties)

#import "GTLEventsConnectasticCreateEventRsp.h"

// ----------------------------------------------------------------------------
//
//   GTLEventsConnectasticCreateEventRsp
//

@implementation GTLEventsConnectasticCreateEventRsp
@dynamic eventId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"event_id"
                                forKey:@"eventId"];
  return map;
}

@end
