/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLEventsConnectasticEventRsp.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events
// Classes:
//   GTLEventsConnectasticEventRsp (0 custom class methods, 11 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLEventsConnectasticPersonRsp;
@class GTLEventsConnectasticRecommendationRsp;
@class GTLEventsConnectasticVenueRsp;

// ----------------------------------------------------------------------------
//
//   GTLEventsConnectasticEventRsp
//

@interface GTLEventsConnectasticEventRsp : GTLObject
@property (retain) NSNumber *createdAt;  // longLongValue
@property (retain) NSNumber *date;  // longLongValue
@property (copy) NSString *eventId;
@property (retain) NSNumber *isOwner;  // boolValue
@property (copy) NSString *name;
@property (retain) GTLEventsConnectasticPersonRsp *owner;
@property (retain) NSArray *participantFbIds;  // of NSNumber (longLongValue)
@property (retain) NSArray *participants;  // of GTLEventsConnectasticPersonRsp
@property (retain) NSArray *recommendations;  // of GTLEventsConnectasticRecommendationRsp
@property (retain) GTLEventsConnectasticVenueRsp *selectedVenue;
@property (copy) NSString *type;
@end
