/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLEvents_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events

#import "GTLEventsConstants.m"

#import "GTLEventsConnectasticCreateEventRsp.m"
#import "GTLEventsConnectasticEventRsp.m"
#import "GTLEventsConnectasticEventsRsp.m"
#import "GTLEventsConnectasticModifyEventReq.m"
#import "GTLEventsConnectasticNewEventReq.m"
#import "GTLEventsConnectasticParticipantReq.m"
#import "GTLEventsConnectasticPersonRsp.m"
#import "GTLEventsConnectasticRecommendationRsp.m"
#import "GTLEventsConnectasticUpdateParticipantsReq.m"
#import "GTLEventsConnectasticVenueRsp.m"

#import "GTLQueryEvents.m"
#import "GTLServiceEvents.m"
