/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLEventsConnectasticNewEventReq.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events
// Classes:
//   GTLEventsConnectasticNewEventReq (0 custom class methods, 6 custom properties)

#import "GTLEventsConnectasticNewEventReq.h"

#import "GTLEventsConnectasticParticipantReq.h"

// ----------------------------------------------------------------------------
//
//   GTLEventsConnectasticNewEventReq
//

@implementation GTLEventsConnectasticNewEventReq
@dynamic date, name, owner, participants, token, type;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLEventsConnectasticParticipantReq class]
                                forKey:@"participants"];
  return map;
}

@end
