/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLGeocodeConnectasticReverseGeoRsp.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   geocode/v1
// Description:
//   Geo- and reverse geo-coding
// Classes:
//   GTLGeocodeConnectasticReverseGeoRsp (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLGeocodeConnectasticReverseGeoRsp
//

@interface GTLGeocodeConnectasticReverseGeoRsp : GTLObject
@property (nonatomic, copy) NSString *address;
@end
