/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLGeocode_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   geocode/v1
// Description:
//   Geo- and reverse geo-coding

#import "GTLGeocodeConstants.m"

#import "GTLGeocodeConnectasticReverseGeoReq.m"
#import "GTLGeocodeConnectasticReverseGeoRsp.m"

#import "GTLQueryGeocode.m"
#import "GTLServiceGeocode.m"
