/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLGeocodeConnectasticReverseGeoRsp.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   geocode/v1
// Description:
//   Geo- and reverse geo-coding
// Classes:
//   GTLGeocodeConnectasticReverseGeoRsp (0 custom class methods, 1 custom properties)

#import "GTLGeocodeConnectasticReverseGeoRsp.h"

// ----------------------------------------------------------------------------
//
//   GTLGeocodeConnectasticReverseGeoRsp
//

@implementation GTLGeocodeConnectasticReverseGeoRsp
@dynamic address;
@end
