/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLGeocodeConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   geocode/v1
// Description:
//   Geo- and reverse geo-coding

#import "GTLGeocodeConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeGeocodeUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
