/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLGeocodeConnectasticReverseGeoReq.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   geocode/v1
// Description:
//   Geo- and reverse geo-coding
// Classes:
//   GTLGeocodeConnectasticReverseGeoReq (0 custom class methods, 2 custom properties)

#import "GTLGeocodeConnectasticReverseGeoReq.h"

// ----------------------------------------------------------------------------
//
//   GTLGeocodeConnectasticReverseGeoReq
//

@implementation GTLGeocodeConnectasticReverseGeoReq
@dynamic latitude, longitude;
@end
