/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryAuth.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   auth/v1
// Description:
//   Logs users in and out, and retrieves a user's details.
// Classes:
//   GTLQueryAuth (5 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLAuthConnectasticAuthReq;
@class GTLAuthConnectasticRecordInvitationsReq;
@class GTLAuthConnectasticRegisterReq;
@class GTLAuthConnectasticWaitlistReq;

@interface GTLQueryAuth : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

#pragma mark - Service level methods
// These create a GTLQueryAuth object.

// Method: auth.login
//  Authorization scope(s):
//   kGTLAuthScopeAuthUserinfoEmail
// Fetches a GTLAuthConnectasticAuthRsp.
+ (instancetype)queryForLoginWithObject:(GTLAuthConnectasticAuthReq *)object;

// Method: auth.logout
//  Authorization scope(s):
//   kGTLAuthScopeAuthUserinfoEmail
+ (instancetype)queryForLogoutWithObject:(GTLAuthConnectasticAuthReq *)object;

// Method: auth.record_invitation
//  Authorization scope(s):
//   kGTLAuthScopeAuthUserinfoEmail
+ (instancetype)queryForRecordInvitationWithObject:(GTLAuthConnectasticRecordInvitationsReq *)object;

// Method: auth.register
//  Authorization scope(s):
//   kGTLAuthScopeAuthUserinfoEmail
// Fetches a GTLAuthConnectasticAuthRsp.
+ (instancetype)queryForRegisterWithObject:(GTLAuthConnectasticRegisterReq *)object;

// Method: auth.waitlist
//  Authorization scope(s):
//   kGTLAuthScopeAuthUserinfoEmail
+ (instancetype)queryForWaitlistWithObject:(GTLAuthConnectasticWaitlistReq *)object;

@end
