/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryGeocode.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   geocode/v1
// Description:
//   Geo- and reverse geo-coding
// Classes:
//   GTLQueryGeocode (1 custom class methods, 1 custom properties)

#import "GTLQueryGeocode.h"

#import "GTLGeocodeConnectasticReverseGeoReq.h"
#import "GTLGeocodeConnectasticReverseGeoRsp.h"

@implementation GTLQueryGeocode

@dynamic fields;

#pragma mark - Service level methods
// These create a GTLQueryGeocode object.

+ (instancetype)queryForReverseWithObject:(GTLGeocodeConnectasticReverseGeoReq *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"geocode.reverse";
  GTLQueryGeocode *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLGeocodeConnectasticReverseGeoRsp class];
  return query;
}

@end
