/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryDeviceregistration.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   deviceregistration/v1
// Description:
//   Registers and un-registers devices
// Classes:
//   GTLQueryDeviceregistration (3 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLDeviceregistrationConnectasticDeviceReq;

@interface GTLQueryDeviceregistration : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryDeviceregistration object.

// Method: deviceregistration.check
//  Authorization scope(s):
//   kGTLAuthScopeDeviceregistrationUserinfoEmail
// Fetches a GTLDeviceregistrationConnectasticDeviceExistsRsp.
+ (id)queryForCheckWithObject:(GTLDeviceregistrationConnectasticDeviceReq *)object;

// Method: deviceregistration.register
//  Authorization scope(s):
//   kGTLAuthScopeDeviceregistrationUserinfoEmail
+ (id)queryForRegisterWithObject:(GTLDeviceregistrationConnectasticDeviceReq *)object;

// Method: deviceregistration.unregister
//  Authorization scope(s):
//   kGTLAuthScopeDeviceregistrationUserinfoEmail
+ (id)queryForUnregisterWithObject:(GTLDeviceregistrationConnectasticDeviceReq *)object;

@end
