/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryGeocode.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   geocode/v1
// Description:
//   Geo- and reverse geo-coding
// Classes:
//   GTLQueryGeocode (1 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLGeocodeConnectasticReverseGeoReq;

@interface GTLQueryGeocode : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

#pragma mark - Service level methods
// These create a GTLQueryGeocode object.

// Method: geocode.reverse
//  Authorization scope(s):
//   kGTLAuthScopeGeocodeUserinfoEmail
// Fetches a GTLGeocodeConnectasticReverseGeoRsp.
+ (instancetype)queryForReverseWithObject:(GTLGeocodeConnectasticReverseGeoReq *)object;

@end
