/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryAuth.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   auth/v1
// Description:
//   Logs users in and out, and retrieves a user's details.
// Classes:
//   GTLQueryAuth (4 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLAuthConnectasticAuthReq;
@class GTLAuthConnectasticRecordInvitationsReq;
@class GTLAuthConnectasticRegisterReq;

@interface GTLQueryAuth : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryAuth object.

// Method: auth.login
//  Authorization scope(s):
//   kGTLAuthScopeAuthUserinfoEmail
// Fetches a GTLAuthConnectasticAuthRsp.
+ (id)queryForLoginWithObject:(GTLAuthConnectasticAuthReq *)object;

// Method: auth.logout
//  Authorization scope(s):
//   kGTLAuthScopeAuthUserinfoEmail
+ (id)queryForLogoutWithObject:(GTLAuthConnectasticAuthReq *)object;

// Method: auth.record_invitation
//  Authorization scope(s):
//   kGTLAuthScopeAuthUserinfoEmail
+ (id)queryForRecordInvitationWithObject:(GTLAuthConnectasticRecordInvitationsReq *)object;

// Method: auth.register
//  Authorization scope(s):
//   kGTLAuthScopeAuthUserinfoEmail
// Fetches a GTLAuthConnectasticAuthRsp.
+ (id)queryForRegisterWithObject:(GTLAuthConnectasticRegisterReq *)object;

@end
