/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryEvents.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   events/v1
// Description:
//   Handles events
// Classes:
//   GTLQueryEvents (9 custom class methods, 4 custom properties)

#import "GTLQueryEvents.h"

#import "GTLEventsConnectasticCreateEventRsp.h"
#import "GTLEventsConnectasticEventRsp.h"
#import "GTLEventsConnectasticEventsRsp.h"
#import "GTLEventsConnectasticModifyEventReq.h"
#import "GTLEventsConnectasticNewEventReq.h"
#import "GTLEventsConnectasticUpdateParticipantsReq.h"

@implementation GTLQueryEvents

@dynamic eventId, fields, identifier, token;

+ (NSDictionary *)parameterNameMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"event_id", @"eventId",
      @"id", @"identifier",
      nil];
  return map;
}

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryEvents object.

+ (id)queryForCancelWithIdentifier:(NSString *)identifier
                             token:(NSString *)token {
  NSString *methodName = @"events.cancel";
  GTLQueryEvents *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  query.token = token;
  return query;
}

+ (id)queryForCreateWithObject:(GTLEventsConnectasticNewEventReq *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"events.create";
  GTLQueryEvents *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLEventsConnectasticCreateEventRsp class];
  return query;
}

+ (id)queryForEditWithObject:(GTLEventsConnectasticModifyEventReq *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"events.edit";
  GTLQueryEvents *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  return query;
}

+ (id)queryForGetWithIdentifier:(NSString *)identifier
                          token:(NSString *)token {
  NSString *methodName = @"events.get";
  GTLQueryEvents *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  query.token = token;
  query.expectedObjectClass = [GTLEventsConnectasticEventRsp class];
  return query;
}

+ (id)queryForListDetailsWithIdentifier:(NSString *)identifier
                                  token:(NSString *)token {
  NSString *methodName = @"events.list_details";
  GTLQueryEvents *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  query.token = token;
  query.expectedObjectClass = [GTLEventsConnectasticEventsRsp class];
  return query;
}

+ (id)queryForListSummaryWithIdentifier:(NSString *)identifier
                                  token:(NSString *)token {
  NSString *methodName = @"events.list_summary";
  GTLQueryEvents *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  query.token = token;
  query.expectedObjectClass = [GTLEventsConnectasticEventsRsp class];
  return query;
}

+ (id)queryForPickWithEventId:(NSString *)eventId
                   identifier:(NSString *)identifier
                        token:(NSString *)token {
  NSString *methodName = @"events.pick";
  GTLQueryEvents *query = [self queryWithMethodName:methodName];
  query.eventId = eventId;
  query.identifier = identifier;
  query.token = token;
  return query;
}

+ (id)queryForUnpickWithIdentifier:(NSString *)identifier
                             token:(NSString *)token {
  NSString *methodName = @"events.unpick";
  GTLQueryEvents *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  query.token = token;
  return query;
}

+ (id)queryForUpdateParticipantsWithObject:(GTLEventsConnectasticUpdateParticipantsReq *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"events.update_participants";
  GTLQueryEvents *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  return query;
}

@end
